version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: dataweave_postgres
    environment:
      POSTGRES_USER: groove_admin
      POSTGRES_PASSWORD: groove_password_dev
      POSTGRES_DB: dataweave_db
    ports:
      - "5432:5432"
    volumes:
      - dataweave_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dataweave_pg_data:
